# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 92e9d082a0bd7f0634baad3d6be05f7c48a5e4928b03c0036c8aeff1dcebc4c0c8106b79f9f9bfe80ad3fa11bcc53940c1401e9aa1c6d67c85bfbb9d0f303248

test:
  secret_key_base: bf4c0ea8947de516e056d0afe79f41939dc104b323401864c6e49f039bc725b7b61a2ed7d8562076902ead3e2c82272cdb264ed140f79f7e280a177c6a01b6f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
